# General GitHub Repository Settings
repository:
  license: MIT      # Select a license from the options below

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: dropbox                           # A unique namespace for your toolbox
  toolbox_name: Dropbox-MATLAB                      # Name of the MATLAB toolbox                  
  author_name: Eivind Hennestad                     
  author_email: ehennestad@gmail.com         
  author_company: N/A                               # Author's company or organization
  toolbox_summary: Unofficial Dropbox File API V2 SDK for MATLAB
  toolbox_description: |
    Class-based Dropbox File API-Client for uploading and downloading files from Dropbox. Users can log in via the browser, so credentials are not stored in MATLAB. The client has the following functions:
     - uploadFile (Files up to 350GB, with progress monitor)
     - downloadFile (With progress monitor)
     - listFolder
     - createFolder
     - getMetadata
     - search
     - move
     - copy
     - getTemporaryDownloadLink
     - getTemporaryUploadLink
     
