function testToolbox(varargin)
    projectRootDirectory = dropboxtools.projectdir();
    matbox.tasks.testToolbox(projectRootDirectory, ...
        "SourceFolderName", "code", ...
        "TestsFolderName", fullfile("tools", "tests"), ...
        varargin{:})
end
