name: Test code

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*md'
      - '.github/**'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*md'
      - '.github/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-code:
    name: Analyse and test code
    uses: ehennestad/matbox-actions/.github/workflows/test-code-workflow.yml@v1
    with:
      # Path to directory with code. Code coverage and code analysis will run 
      # on the contents of the specified folder (and subfolders)
      source_directory: src
      
      # Path to directory containing tests. This directory will be used for 
      # locating MATLAB  test suites
      tests_directory: tests
      
      # Path to directory with (CI) tools or tests. Used for finding unit tests
      # and running customized MatBox tasks
      tools_directory: tools

      # Name of MATLAB Release to use for running test suites and code analysis
      matlab_release: latest
      
      # Whether to cache the MATLAB installation for faster subsequent setups
      matlab_use_cache: false
      
      # Optional list of MATLAB products to install. Example if adding multiple 
      # products (use ">" and one product per line):
      # matlab_products: >
      #   Image_Processing_Toolbox
      #   Statistics_and_Machine_Learning_Toolbox
